services:
  speech:
    # image: ghcr.io/matatonic/openedai-speech
    #image: registry.rodox.dns.army/openedai-speech:deepspeed
    image: registry.rodox.dns.army/openedai-speech
    #pull_policy: always
    environment:
      - LOG=DEBUG # DEBUG,INFO,WARNING,ERROR,CRITICAL
      - PRELOAD_MODEL=xtts
        #- TIMER=--unload-timer 600
      - EXTRA_ARGS=
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

